### PR TITLE
Use original node code

### PR DESCRIPTION
**Pull request by jscissr**
These are the changes discussed in https://github.com/devongovett/browserify-zlib/pull/18.

Now, the the original node code is used for src/index.js and tests, with only requires changed. For this to work, a build system is introduced; meaning the package published to npm will use the files in `lib`, not `src`. When running `npm test`, these files are automatically generated.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
@jscissr this is pretty awesome :) thank you for doing this! 

Is this now up to date with nodejs/node#master?

**Comment by jscissr** [comment]
No, with v6.3.1 (latest)

**Comment by dignifiedquire** [comment]
Just reviewed the critical changes in `binding.js` and all looks 👍  to me, so if CI is happy I will merge it. And then hopefully we can merge it upstream soon :)

**Comment by dignifiedquire** [comment]
@jscissr looks like the tests are not executing on travis

**Comment by jscissr** [comment]
I'm investigating...

**Comment by jscissr** [comment]
It looks like this only works on v6.3.1. Is it ok to remove the v4 and v5 node versions?

**Comment by dignifiedquire** [comment]
Yeah makes sense

**Comment by dignifiedquire** [comment]
Thank you :octocat:

**Pull request merged**
